import './style.css';
import './DirectionalPad.css';
import './InteractionMenu.css';
import { FaceDetector, FilesetResolver } from '@mediapipe/tasks-vision';
import { initInputs } from './Interface/InteractionMenu';
import { initScaling } from './scaling';
import { clearImageFace, initThree, setImageFace } from './three/threeLoader';
import type { FaceBuildProgress } from './faceverse/FaceVerseLite';

type ImageTransform={x:number;y:number;scale:number}; type FaceSource='3d'|'image'; type EditorSnapshot={source:FaceSource;transform:ImageTransform}; type FaceBox=[number,number,number,number];
const FACE_DETECTOR_MODEL='https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite';
const FACE_DETECTOR_WASM='https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.35/wasm'; let faceDetectorPromise:Promise<FaceDetector>|null=null;
async function getFaceDetector(){if(!faceDetectorPromise)faceDetectorPromise=(async()=>{const vision=await FilesetResolver.forVisionTasks(FACE_DETECTOR_WASM);return FaceDetector.createFromModelPath(vision,FACE_DETECTOR_MODEL);})();return faceDetectorPromise;}

function initNavigation(){
 const navbar=document.getElementById('navbar') as HTMLDivElement|null,menuButton=document.getElementById('menu-button') as HTMLButtonElement|null,menu=document.getElementById('app-menu') as HTMLDivElement|null,imageUpload=document.getElementById('image-upload') as HTMLInputElement|null,imageUploadMenuItem=document.getElementById('image-upload-menu-item') as HTMLButtonElement|null,threeModelMenuItem=document.getElementById('three-model-menu-item') as HTMLButtonElement|null,adjustImageMenuItem=document.getElementById('adjust-image-menu-item') as HTMLButtonElement|null,canvas=document.getElementById('canvas') as HTMLCanvasElement|null,imageBackground=document.getElementById('image-background') as HTMLImageElement|null,imagePreview=document.getElementById('image-preview') as HTMLImageElement|null,imageEditor=document.getElementById('image-editor') as HTMLDivElement|null,interactionMenu=document.getElementById('interaction-menu') as HTMLDivElement|null,imageZoom=document.getElementById('image-zoom') as HTMLInputElement|null,imageDoneButton=document.getElementById('image-done-button') as HTMLButtonElement|null,imageEditorFrame=document.getElementById('image-editor-frame') as HTMLDivElement|null,imageEditorHint=document.getElementById('image-editor-hint') as HTMLDivElement|null,reconstructionStatus=document.getElementById('reconstruction-status') as HTMLDivElement|null,reconstructionStage=document.getElementById('reconstruction-stage') as HTMLDivElement|null,reconstructionDetail=document.getElementById('reconstruction-detail') as HTMLDivElement|null,reconstructionProgress=document.getElementById('reconstruction-progress-bar') as HTMLDivElement|null,reconstructionMetric=document.getElementById('reconstruction-metric') as HTMLDivElement|null;
 if(!navbar||!menuButton||!menu||!imageUpload||!imageUploadMenuItem||!threeModelMenuItem||!adjustImageMenuItem||!canvas||!imageBackground||!imagePreview||!imageEditor||!interactionMenu||!imageZoom||!imageDoneButton||!imageEditorFrame||!imageEditorHint||!reconstructionStatus||!reconstructionStage||!reconstructionDetail||!reconstructionProgress||!reconstructionMetric)return;
 let imageObjectUrl:string|null=null,activeSource:FaceSource='3d',imageRendered=false,transform:ImageTransform={x:0,y:0,scale:1},dragStart:{pointerId:number;x:number;y:number;startX:number;startY:number}|null=null,editorSnapshot:EditorSnapshot|null=null,editorResetTransform:ImageTransform={x:0,y:0,scale:1},detectedFaceBox:FaceBox|null=null,reconstructionController:AbortController|null=null,reconstructionStartedAt=0,downloadModel={loaded:0,total:0},downloadGeometry={loaded:0,total:0};
 const setMenuOpen=(open:boolean)=>{menu.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));}; const copyTransform=(v:ImageTransform)=>({...v});
 const updateModeUI=()=>{const usingImage=activeSource==='image',showRenderedImage=usingImage&&imageRendered;canvas.style.visibility=showRenderedImage||!usingImage?'visible':'hidden';imageBackground.hidden=!usingImage||imageRendered;imagePreview.hidden=!usingImage||imageRendered;imageUploadMenuItem.hidden=usingImage;threeModelMenuItem.hidden=!usingImage;adjustImageMenuItem.hidden=!usingImage||!imageRendered||!imageEditor.hidden;};
 const setSource=(source:FaceSource)=>{activeSource=source;if(source==='3d'){imageRendered=false;clearImageFace();}updateModeUI();};
 const applyImageTransform=()=>{imagePreview.style.transform=`translate3d(${transform.x}px,${transform.y}px,0) scale(${transform.scale})`;imageZoom.value=String(transform.scale);}; const resetImageTransform=()=>{transform=copyTransform(editorResetTransform);applyImageTransform();};
 const setEditorOpen=(open:boolean,snapshot?:EditorSnapshot)=>{if(open){editorSnapshot=snapshot??{source:activeSource,transform:copyTransform(transform)};editorResetTransform=copyTransform(transform);setMenuOpen(false);interactionMenu.hidden=true;interactionMenu.setAttribute('aria-hidden','true');navbar.classList.add('editor-active');menuButton.setAttribute('aria-label','Cancel image adjustment');menuButton.setAttribute('aria-expanded','false');imageEditor.hidden=false;applyImageTransform();return;}imageEditor.hidden=true;interactionMenu.hidden=false;interactionMenu.removeAttribute('aria-hidden');navbar.classList.remove('editor-active');menuButton.setAttribute('aria-label','Open menu');menuButton.setAttribute('aria-expanded','false');editorSnapshot=null;dragStart=null;};
 const cancelEditor=()=>{if(!editorSnapshot){setEditorOpen(false);return;}transform=copyTransform(editorSnapshot.transform);setSource(editorSnapshot.source);applyImageTransform();setEditorOpen(false);};
 const autoFitToFace=async()=>{try{await imagePreview.decode();const detector=await getFaceDetector(),detections=detector.detect(imagePreview).detections;if(!detections.length){detectedFaceBox=null;imageEditorHint.textContent='No face detected — position it manually';return;}const detection=[...detections].sort((a,b)=>(b.categories[0]?.score??0)-(a.categories[0]?.score??0))[0];if(!detection){detectedFaceBox=null;imageEditorHint.textContent='No face detected — position it manually';return;}const box=detection.boundingBox;if(!box){detectedFaceBox=null;imageEditorHint.textContent='Face location unavailable — position it manually';return;}detectedFaceBox=[box.originX,box.originY,box.originX+box.width,box.originY+box.height];const width=imagePreview.clientWidth,height=imagePreview.clientHeight,naturalWidth=imagePreview.naturalWidth,naturalHeight=imagePreview.naturalHeight,coverScale=Math.max(width/naturalWidth,height/naturalHeight),renderedWidth=naturalWidth*coverScale,renderedHeight=naturalHeight*coverScale,baseLeft=(width-renderedWidth)/2,baseTop=(height-renderedHeight)/2,faceX=baseLeft+(box.originX+box.width/2)*coverScale,faceY=baseTop+(box.originY+box.height/2)*coverScale,faceHeight=box.height*coverScale,targetFaceHeight=Math.min(height*.38,width*.68),targetX=width/2,targetY=height*.40,scale=Math.min(2.5,Math.max(.65,targetFaceHeight/faceHeight));transform.scale=scale;transform.x=targetX-(width/2+(faceX-width/2)*scale);transform.y=targetY-(height/2+(faceY-height/2)*scale);editorResetTransform=copyTransform(transform);applyImageTransform();imageEditorHint.textContent='Face fitted — drag or zoom to fine-tune';}catch{detectedFaceBox=null;imageEditorHint.textContent='Auto-fit unavailable — position it manually';}};
 const formatBytes=(n:number)=>n<1024*1024?`${(n/1024).toFixed(0)} KB`:`${(n/1024/1024).toFixed(1)} MB`;
 const updateReconstructionProgress=(p:FaceBuildProgress)=>{const elapsed=Math.max((performance.now()-reconstructionStartedAt)/1000,.1);if(p.stage==='download-model')downloadModel={loaded:p.loaded??downloadModel.loaded,total:p.total??downloadModel.total};if(p.stage==='download-geometry')downloadGeometry={loaded:p.loaded??downloadGeometry.loaded,total:p.total??downloadGeometry.total};const loaded=downloadModel.loaded+downloadGeometry.loaded,total=downloadModel.total+downloadGeometry.total;if(p.stage==='download-model'||p.stage==='download-geometry'){reconstructionStage.textContent='Downloading 3D reconstruction';reconstructionDetail.textContent=p.stage==='download-model'?'Reconstruction model':'3D face geometry';reconstructionMetric.textContent=total>0?`${formatBytes(loaded)} / ${formatBytes(total)} · ${(loaded/elapsed/1024/1024).toFixed(1)} MB/s`:`${formatBytes(loaded)} downloaded`;reconstructionProgress.style.width=total>0?`${Math.min(100,loaded/total*100)}%`:'28%';}else if(p.stage==='initialize'){reconstructionStage.textContent='Initializing 3D engine';reconstructionDetail.textContent='Preparing the browser inference runtime';reconstructionMetric.textContent='Almost ready';reconstructionProgress.style.width='76%';}else if(p.stage==='inference'){reconstructionStage.textContent='Reconstructing your face';reconstructionDetail.textContent='Fitting identity and facial geometry';reconstructionMetric.textContent='Running locally on this device';reconstructionProgress.style.width='88%';}else{reconstructionStage.textContent='Building 3D model';reconstructionDetail.textContent='Creating the mesh and preparing controls';reconstructionMetric.textContent='Finalizing';reconstructionProgress.style.width='96%';}};
 const showReconstruction=()=>{reconstructionStartedAt=performance.now();downloadModel={loaded:0,total:0};downloadGeometry={loaded:0,total:0};reconstructionProgress.style.width='0%';reconstructionStage.textContent='Preparing 3D face';reconstructionDetail.textContent='Starting reconstruction…';reconstructionMetric.textContent='First run may take longer';reconstructionStatus.hidden=false;navbar.classList.add('reconstruction-active');menuButton.setAttribute('aria-label','Cancel reconstruction');menuButton.setAttribute('aria-expanded','false');interactionMenu.hidden=true;imageEditor.hidden=true;};
 const finishReconstruction=()=>{reconstructionStatus.hidden=true;navbar.classList.remove('reconstruction-active');menuButton.setAttribute('aria-label','Open menu');interactionMenu.hidden=false;};
 const cancelReconstruction=()=>{reconstructionController?.abort();reconstructionController=null;reconstructionStatus.hidden=true;navbar.classList.remove('reconstruction-active');imageRendered=false;imageEditor.hidden=false;interactionMenu.hidden=true;imageEditorHint.textContent='Reconstruction cancelled — adjust and try again';menuButton.setAttribute('aria-label','Cancel image adjustment');imageDoneButton.disabled=false;};
 menuButton.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();if(!imageEditor.hidden&&reconstructionStatus.hidden){cancelEditor();return;}if(!reconstructionStatus.hidden){cancelReconstruction();return;}setMenuOpen(menu.hidden);});
 menu.addEventListener('click',e=>e.stopPropagation());
 imageUploadMenuItem.addEventListener('click',e=>{e.preventDefault();setMenuOpen(false);imageUpload.click();});
 threeModelMenuItem.addEventListener('click',e=>{e.preventDefault();setSource('3d');setMenuOpen(false);});
 adjustImageMenuItem.addEventListener('click',e=>{e.preventDefault();setEditorOpen(true);});
 imageUpload.addEventListener('change',()=>{const file=imageUpload.files?.[0];if(!file||!file.type.startsWith('image/'))return;const previousState:EditorSnapshot={source:activeSource,transform:copyTransform(transform)};if(imageObjectUrl)URL.revokeObjectURL(imageObjectUrl);imageObjectUrl=URL.createObjectURL(file);imagePreview.src=imageObjectUrl;imageBackground.src=imageObjectUrl;transform={x:0,y:0,scale:1};detectedFaceBox=null;imageRendered=false;setSource('image');imageEditorHint.textContent='Finding face…';requestAnimationFrame(()=>{setEditorOpen(true,previousState);void autoFitToFace();});});
 imagePreview.addEventListener('error',()=>cancelEditor());
 imageZoom.addEventListener('input',()=>{transform.scale=Number(imageZoom.value);applyImageTransform();});
 imageDoneButton.addEventListener('click',async e=>{e.preventDefault();if(imageDoneButton.disabled)return;imageDoneButton.disabled=true;showReconstruction();reconstructionController=new AbortController();try{const built=await setImageFace(imagePreview,detectedFaceBox??undefined,updateReconstructionProgress,reconstructionController.signal);if(!built)throw new Error('The 3D renderer is not ready');imageRendered=true;reconstructionProgress.style.width='100%';reconstructionStage.textContent='3D face ready';reconstructionDetail.textContent='Your face is now a real interactive mesh';reconstructionMetric.textContent='Ready';await new Promise(r=>setTimeout(r,350));finishReconstruction();updateModeUI();}catch(error){if(error instanceof DOMException&&error.name==='AbortError')return;console.error(error);reconstructionStage.textContent='Reconstruction failed';reconstructionDetail.textContent=error instanceof Error?error.message:'The 3D face could not be built';reconstructionMetric.textContent='Try again';reconstructionProgress.style.width='0%';imageEditorHint.textContent='Reconstruction failed — adjust and try again';await new Promise(r=>setTimeout(r,900));reconstructionStatus.hidden=true;navbar.classList.remove('reconstruction-active');imageEditor.hidden=false;interactionMenu.hidden=true;menuButton.setAttribute('aria-label','Cancel image adjustment');}finally{reconstructionController=null;imageDoneButton.disabled=false;}});
 imageEditorFrame.addEventListener('pointerdown',event=>{if(event.pointerType==='mouse'&&event.button!==0)return;event.preventDefault();imageEditorFrame.setPointerCapture(event.pointerId);dragStart={pointerId:event.pointerId,x:event.clientX,y:event.clientY,startX:transform.x,startY:transform.y};});
 imageEditorFrame.addEventListener('pointermove',event=>{if(!dragStart||dragStart.pointerId!==event.pointerId)return;event.preventDefault();transform.x=dragStart.startX+event.clientX-dragStart.x;transform.y=dragStart.startY+event.clientY-dragStart.y;applyImageTransform();});
 const endDrag=(event:PointerEvent)=>{if(dragStart?.pointerId===event.pointerId)dragStart=null;}; imageEditorFrame.addEventListener('pointerup',endDrag);imageEditorFrame.addEventListener('pointercancel',endDrag);
 document.addEventListener('click',event=>{if(!menu.hidden&&!menu.contains(event.target as Node)&&event.target!==menuButton)setMenuOpen(false);});
 setSource('3d');resetImageTransform();
}
initNavigation();initInputs();initScaling();initThree();
